In [1]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [56]:
# No.10

# X = np.array([[2.7,3.2,-0.4,0.6,1.8,2.1],[4.8,5.1,-0.3,0.5,2.8,4.3]])
Xp = [[[2.7],[4.8]],[[3.2],[5.1]],[[-0.4],[-0.3]]]
Xn = [[[0.6],[0.5]],[[1.8],[2.8]],[[2.1],[4.3]]]
Xp = np.array(Xp)
Xn = np.array(Xn)
Xp.shape
miu_p = np.mean(Xp, axis=0)
miu_n = np.mean(Xn, axis=0)

sigma_p = np.array([[0.,0.],[0.,0.]])
sigma_n = np.array([[0.,0.],[0.,0.]])
for i in range(3):
    sigma_p += ((Xp[i,:,:]-miu_p).dot((Xp[i,:,:]-miu_p).T))
    sigma_n += ((Xn[i,:,:]-miu_n) * (Xn[i,:,:]-miu_n).T)
sigma_p /= 3
sigma_n /= 3

print('class +:')
print('miu:')
miu_p
print('sigma:')
sigma_p
print('class -:')
print('miu:')
miu_n
print('sigma:')
sigma_n


(3, 2, 1)

class +:
miu:


array([[1.83333333],
       [3.2       ]])

sigma:


array([[2.53555556, 3.93333333],
       [3.93333333, 6.14      ]])

class -:
miu:


array([[1.5       ],
       [2.53333333]])

sigma:


array([[0.42      , 0.99      ],
       [0.99      , 2.44222222]])

In [59]:
x = [[1.6],[2.3]]
px_p = np.log(1/(2*np.pi*np.sqrt(np.linalg.det(sigma_p)))) - (x-miu_p).T.dot(np.linalg.inv(sigma_p)).dot(x-miu_p) / 2
px_n = np.log(1/(2*np.pi*np.sqrt(np.linalg.det(sigma_n)))) - (x-miu_n).T.dot(np.linalg.inv(sigma_n)).dot(x-miu_n) / 2
print('log p(x|+) = ', px_p)
print('log p(x|-) = ', px_n)

log p(x|+) =  [[-4.45885026]]
log p(x|-) =  [[-1.31866732]]


In [2]:
# No.3

X = [[1, 362],[1, 529],[1, 790],[1, 401],[1, 380],[1, 1454],[1, 1127],[1, 700],[1, 1050],[1, 428]]
X = np.array(X)
# x = [[1] for _ in range(len(X))]
# x = np.array(x)
# X = np.concatenate((x, X), axis=1)
X.shape
y = [[26],[40],[60],[22],[38],[110],[100],[46],[57],[28]]
y = np.array(y)
y.shape

W = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
W

(10, 2)

(10, 1)

array([[-1.97639231],
       [ 0.07571859]])

In [186]:
class LinearRegression:
    def __init__(self, alpha=0.000001, reg_lambda=0.0):
        self.alpha = alpha
        self.w0 = 0
        self.w1 = 0.1
        
    def forward(self, X, w0, w1):
        """
        param x: height
        param w0,w1: weight using for predict y
        return: float: predict value
        """
        _y = w1 * X + w0
        return _y

    def costFunction(self, _y, y):
        cost = np.sum((_y-y) ** 2) / 10
        return cost

    def backward(self, X, w0, w1, y):
        _y = self.forward(X, w0, w1)
        dw0 = np.sum(_y-y) / X.shape[0]
        dw1 = np.sum(np.multiply((_y-y), X)) / X.shape[0]
        return dw0, dw1

    def train(self, X, y):
        for b in range(25):
            w0, w1 = self.w0, self.w1
            for i in range(10):
                dw0, dw1 = self.backward(X, w0, w1, y)
                w0 -= self.alpha*(10**6) * dw0
                w1 -= self.alpha * dw1
                _y = self.forward(X, w0, w1)
                cost = self.costFunction(_y, y)
            self.updateParameters(w0, w1)
            print('Epoch', b+1, w0, w1, cost)
        return w0, w1
    
    def updateParameters(self, w0, w1):
        self.w0 = w0
        self.w1 = w1


In [188]:
lg_model = LinearRegression(alpha=0.000001)
w0, w1 = lg_model.train(X, y)
w0, w1

Epoch 1 -6.6246558817988115 0.08172152672554464 95.53582019904147
Epoch 2 -3.971173200539998 0.07825485300075692 91.65779502673135
Epoch 3 -2.824277002997446 0.0767964932518609 90.95821742020767
Epoch 4 -2.3367587324489056 0.07617671679523133 90.83184557002724
Epoch 5 -2.1295544971633675 0.0759133008781107 90.80901772957642
Epoch 6 -2.0414889831048204 0.07580134439337857 90.80489410316036
Epoch 7 -2.0040595614311973 0.07575376088103081 90.80414921032411
Epoch 8 -1.988151386458377 0.07573353703555304 90.80401465270862
Epoch 9 -1.9813901270092567 0.07572494153879947 90.80399034618969
Epoch 10 -1.9785164705768528 0.07572128829864185 90.80398595545441
Epoch 11 -1.9772951150951406 0.07571973560610623 90.80398516231098
Epoch 12 -1.9767760171278699 0.07571907568395327 90.80398501903736
Epoch 13 -1.976555391189173 0.07571879520521198 90.80398499315638
Epoch 14 -1.9764616212114614 0.07571867599672057 90.8039849884812
Epoch 15 -1.9764217672905142 0.07571862533097541 90.80398498763672
Epoch 16 -1

(-1.9763923135505985, 0.07571858788683831)

In [137]:
from sklearn.linear_model import LinearRegression

In [138]:
linear_reg_model = LinearRegression()
linear_reg_model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [139]:
linear_reg_model.intercept_

array([-1.97639231])

In [140]:
linear_reg_model.coef_

array([[0.07571859]])

In [130]:
w0, w1 = -2, 0.076
loss = []
for i in range(10):
    loss.append(abs(y[i]-(w0+w1*X[i][0])))
    print(w0+w1*X[i][0])
print(y)
loss.remove(max(loss))
loss.remove(min(loss))
np.sum(loss), np.var(loss)

25.512
38.204
58.04
28.476
26.88
108.50399999999999
83.652
51.199999999999996
77.8
30.528
[[ 26]
 [ 40]
 [ 60]
 [ 22]
 [ 38]
 [110]
 [100]
 [ 46]
 [ 57]
 [ 28]]


(46.92400000000001, 25.04417174999999)

In [96]:
0.07571859*475-1.9763923078843249
-1.0000023381405847+475*0.07463392268569402
-1 + 475 * 0.0746
-1.6684710167192687 + 475 * 0.07532895892725583
-1.8 + 475 * 0.0755
-1.98 + 475 * 0.0757

33.989937942115674

34.451110937564074

34.435

34.11278447372725

34.0625

33.977500000000006

In [76]:
a1 = [[2],[3],[3]]
a2 = [[1],[1],[1]]
np.concatenate((a2, a1), axis=1)

array([[1, 2],
       [1, 3],
       [1, 3]])

In [78]:
a = [[1] for _ in range(3)]
a

[[1], [1], [1]]

In [59]:
X = [[362],[529],[790],[401],[380],[1454],[1127],[700],[1050],[428]]
X = np.array(X)
X = X
x = [[100] for i in range(X.shape[0])]
X_train = np.concatenate((x, X), axis=1)
X_train
y = [[26],[40],[60],[22],[38],[110],[100],[46],[57],[28]]
y_train = np.array(y)
y_train

array([[ 100,  362],
       [ 100,  529],
       [ 100,  790],
       [ 100,  401],
       [ 100,  380],
       [ 100, 1454],
       [ 100, 1127],
       [ 100,  700],
       [ 100, 1050],
       [ 100,  428]])

array([[ 26],
       [ 40],
       [ 60],
       [ 22],
       [ 38],
       [110],
       [100],
       [ 46],
       [ 57],
       [ 28]])

In [91]:
class LinearRegression2:
    def __init__(self, alpha=0.00001, reg_lambda=0.0):
        self.alpha = alpha
        self.W = [[0.01] for _ in range(2)]
        
    def forward(self, X, W):
        _y = X.dot(W)
        return _y

    def cost(self, _y, y):
        cost = np.sum((_y-y) ** 2)
        return cost

    def backward(self, X, W, y):
        _y = self.forward(X, W)
        dW = X.T.dot(X.dot(W) - y) / X.shape[0]
        return dW

    def train(self, X, y):
        for b in range(151):
            W = self.W
            for i in range(50):
                dW = self.backward(X, W, y)
                W -= self.alpha * dW
            _y = self.forward(X, W)
            RSS = self.cost(_y, y)
            self.updateParameters(W)
            if b%10==0:
                print('Epoch', b+1, W.T, RSS, _y.T)
        return W
    
    def updateParameters(self, W):
        self.W = W

In [95]:
lr = LinearRegression2(alpha=0.000001)
lr.train(X_train, y_train)
y_train

Epoch 1 [[0.01345511 0.07201715]] 929.8698024929903 [[ 27.41571832  39.44258193  58.23905739  30.22438706  28.71202697
  106.05844325  82.50883606  51.75751413  76.96351571  32.16885004]]
Epoch 11 [[-0.00727081  0.07432654]] 911.1274434185152 [[ 26.17912611  38.59165814  57.99088486  29.07786113  27.51700381
  107.34370686  83.03892856  51.30149634  77.31578504  31.08467769]]
Epoch 21 [[-0.01506548  0.07519506]] 908.4765541614828 [[ 25.71406484  38.2716402   57.8975514   28.64667226  27.06757596
  107.82707261  83.23828732  51.12999582  77.44826754  30.67693893]]
Epoch 31 [[-0.01799692  0.0755217 ]] 908.1016166296 [[ 25.53916322  38.15128691  57.86245028  28.48450947  26.89855379
  108.00885824  83.31326275  51.06549739  77.49809195  30.52359533]]
Epoch 41 [[-0.01909938  0.07564454]] 908.0485860654445 [[ 25.4733857   38.10602408  57.84924934  28.4235228   26.83498744
  108.07722471  83.34145973  51.04124063  77.51683006  30.46592542]]
Epoch 51 [[-0.019514    0.07569074]] 908.0410855073

array([[-0.01976391],
       [ 0.07571859]])

array([[ 26],
       [ 40],
       [ 60],
       [ 22],
       [ 38],
       [110],
       [100],
       [ 46],
       [ 57],
       [ 28]])